"""Shared pytest configuration for the Seed Code test suite.

Guarantees for every test:

* a project-local ``.env`` (which may hold a developer's real API key on this
  machine) is never read, so a test outcome can never depend on local secrets;
* the build-only embedded default credential is never available, so a test
  outcome can never depend on a release artifact happening to exist in the
  working tree;
* tests that need environment overrides or the embedded credential still set
  them explicitly with ``monkeypatch.setenv`` / ``monkeypatch.setattr`` and are
  unaffected by these fixtures.

The second guarantee matters in practice: ``scripts/windows/build.bat`` runs
the test suite as a release gate *after* Stage 0b generates
``seedcode/_default_key.py``, so without this fixture the built-in Default
provider would be reachable during a release build but not during a normal
test run — and every "not configured yet" assertion would flip.
"""

from __future__ import annotations

import pytest


@pytest.fixture(autouse=True)
def _disable_dotenv(monkeypatch: pytest.MonkeyPatch) -> None:
    """Keep the developer's ``.env`` out of every test run."""
    monkeypatch.setenv("SEEDCODE_DISABLE_DOTENV", "1")


@pytest.fixture(autouse=True)
def _no_embedded_default_credential(monkeypatch: pytest.MonkeyPatch) -> None:
    """Hide the git-ignored release credential generated by the build pipeline.

    ``seedcode/_default_key.py`` is a build-time artifact. Tests that exercise
    the embedded path patch ``default_api._load_embedded`` back explicitly, so
    patching it here only changes the *default*.
    """
    from seedcode import default_api

    monkeypatch.setattr(default_api, "_load_embedded", lambda: ("", False, "test"))
