"""Generate the embedded default OpenRouter key module (v6.2.5 release builds).

Reads ``OPENROUTER_API_KEY`` from the repository-root ``.env`` (or an
explicit ``--env-file``) and writes ``seedcode/_default_key.py`` — a
git-ignored Python module that ``seedcode/default_api.py`` imports at
runtime. PyInstaller packages the generated module into the frozen
executable, so the released EXE/installer works out of the box.

Security rules enforced here:

* the generated module is written to ``seedcode/_default_key.py``, which the
  repository ``.gitignore`` excludes — it must never be committed;
* the script never prints the key, its length, or any fragment of it;
* ``--clean`` removes the generated file (used after packaging if a caller
  wants the working tree pristine; the build keeps it by default so the
  pip/wheel path is unaffected and the artifact stays reproducible).

The generated file carries a low-value obfuscation (XOR + base64) purely to
avoid a plaintext ``sk-or-...`` string sitting in a temp extraction
directory; it is NOT cryptographic protection. The long-term plan is a
server-side gateway, after which this module disappears.

Usage:
    python scripts/windows/embed_default_key.py            # generate from .env
    python scripts/windows/embed_default_key.py --clean    # remove the module
"""

from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ENV = REPO_ROOT / ".env"
TARGET = REPO_ROOT / "seedcode" / "_default_key.py"

# XOR mask for the stored payload (obfuscation only, not security).
_MASK = b"SeedCode/v6.2.5"


def _obfuscate(key: str) -> str:
    raw = key.encode("utf-8")
    masked = bytes(b ^ _MASK[i % len(_MASK)] for i, b in enumerate(raw))
    return base64.b64encode(masked).decode("ascii")


def _template() -> str:
    return (
        Path(__file__).with_name("_default_key_template.py").read_text(encoding="utf-8")
        if Path(__file__).with_name("_default_key_template.py").exists()
        else ""
    )


def _read_env_value(env_file: Path, name: str) -> str:
    """Extract one variable from a .env file without echoing it."""
    if not env_file.exists():
        return ""
    for line in env_file.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        var, _, value = line.partition("=")
        if var.strip() == name:
            value = value.strip().strip("'\"")
            return value
    return ""


def generate(env_file: Path) -> int:
    key = _read_env_value(env_file, "OPENROUTER_API_KEY")
    if not key:
        print("[ERROR] OPENROUTER_API_KEY not found in %s" % env_file)
        print("        Add it to .env (never commit .env), then re-run.")
        return 2

    payload = _obfuscate(key)
    module = f'''"""Embedded default OpenRouter credential (v6.2.5 build-time artifact).

GENERATED by scripts/windows/embed_default_key.py from the build machine's
.env — DO NOT COMMIT (git-ignored) and DO NOT EDIT by hand. Decoded by
seedcode/default_api.py at runtime. The obfuscation is not a security
boundary; it only keeps the plaintext out of casual file dumps.
"""

from base64 import b64decode

_PAYLOAD = "{payload}"
_MASK = {_MASK!r}

DEFAULT_OPENROUTER_API_KEY = bytes(
    b ^ _MASK[i % len(_MASK)] for i, b in enumerate(b64decode(_PAYLOAD))
).decode("utf-8")
DEFAULT_API_ENABLED = True
DEFAULT_API_NOTE = "embedded Seed Code default API (v6.2.5 release build)"
'''
    TARGET.write_text(module, encoding="utf-8")
    # Never print the key; report only the safe fact that generation happened.
    print(f"[OK] Generated {TARGET} (embedded default key active for release builds)")
    print("     This file is git-ignored; do not commit it.")
    return 0


def clean() -> int:
    if TARGET.exists():
        TARGET.unlink()
        print(f"[OK] Removed {TARGET}")
    else:
        print(f"[INFO] {TARGET} not present (nothing to clean)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--env-file", default=str(DEFAULT_ENV), help="path to the .env file"
    )
    parser.add_argument(
        "--clean", action="store_true", help="remove the generated module"
    )
    opts = parser.parse_args()
    if opts.clean:
        return clean()
    env_file = Path(opts.env_file)
    if not env_file.exists():
        print(f"[ERROR] .env file not found: {env_file}")
        return 2
    return generate(env_file)


if __name__ == "__main__":
    sys.exit(main())
